"""empty message

Revision ID: 1ca0fa7b10f9
Revises: 
Create Date: 2024-05-15 16:39:39.173963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca0fa7b10f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=254), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('completed_datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('border_progress', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('target')
    op.drop_table('user')
    # ### end Alembic commands ###
