"""empty message

Revision ID: 448013955f6d
Revises: 058d97e000f7
Create Date: 2024-05-17 19:52:11.141000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "448013955f6d"
down_revision: Union[str, None] = "058d97e000f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("id", sa.VARCHAR(length=20), nullable=False),
        sa.Column("api", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("api_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column(
            "service_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("api", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("service_id", name="api_key_pkey"),
    )
    op.drop_table("service")
    # ### end Alembic commands ###
