services:
  api:
    depends_on:
      - postgres
    build:
      context: server
    ports:
      - "8000:8000"
    networks:
      - bridge
    environment:
      DATABASE: postgresql+asyncpg://postgres:postgres@postgres:5432
  bot:
    ports:
      - "80:80"
    depends_on:
      - redis
      - api
    build:
      context: client
    environment:
      BACKEND: http://api:8000
      REDIS_HOST: redis
    networks:
      - bridge

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: habits
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - bridge
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bridge


volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
   bridge:
     driver: bridge
